# Generated by Django 4.0.4 on 2022-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
